#https://stackoverflow.com/questions/49967451/api-platform-how-to-document-authentication-routes/49970305#49970305

App\Entity\User:
  collectionOperations:
    POST:
    GET:
    login:
      method: POST
      route_name: api_login
      openapi_context:
        requestBody:
          content:
            'application/json':
              schema:
                properties:
                  username:
                    description: The user's email
                    type: string
                  password:
                    description: The user's password
                    type: string
                required:
                  - password
                  - username

        responses:
          200:
            description: "Successful login attempt, returning a new token"
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string

                password:
                  type: string

        summary: Performs a login attempt, returning a valid token on success
        consumes:
          - "application/json"
        produces:
          - "application/ld-json"